
PATH:
  DATASET_DIR: 'dataset/'
  PKL_PATH: 'dataset/database.pkl'

INFO:
  PICTURE_PROMPT: '`This app recognizes faces in images that are known to the database. To use it, simply press "browse files" and upload an image.`'
  WEBCAM_PROMPT: '`This app recognizes faces in a live video stream that are known to the database. To use it, simply press "capture frame" and allow access to your webcam.`'